export const WHITE = '#FFFFFF'
export const BLACK = '#0a0a0a'
export const BLUE = '#0366d6'
export const BLUE_2 = '#0c63c8'
export const GRAY = '#586069'
export const GRAY_2 = '#BCBCBC'
export const GRAY_3 = '#eef3f3'
export const BACKGROUND = '#eff0f4'
